---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend-service
    app: yolomy-app
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: yolo-backend-pod
    app: yolomy-app