---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-deployment
  labels:
     app: yolomy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: yolo-backend-pod
      app: yolomy-app
  template:
    metadata:
      name: yolo-backend-pod
      labels:
        name: yolo-backend-pod
        app: yolomy-app
    spec:
      containers:
        - name: client
          image: josphatn/yolo_backend:1.0.0
          ports:
            - containerPort: 5000