---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend_service
    app: yolomy_app
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: yolo_backend_pod
    app: yolomy_app