---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-pod
      app: yolomy-app
  template:
    metadata:
      labels:
        name: mongodb-pod
        app: yolomy-app
    spec:
      containers:
        - name: db
          image: mongo:4.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: yolodb
        resources:
          requests:
            storage: 30Gi