---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-StatefulSet
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-pod
      app: yolomy-app
  template:
    metadata:
      name: mongodb-pod
      labels:
        name: mongodb-pod
        app: yolomy-app
    spec:
      containers:
        - name: db
          image: mongo:4.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "mongodb-storage"
        resources:
          requests:
            storage: 200Mi