---
apiVersion: v1
kind: Service
metadata:
  name: yolomy-service
  labels:
    name: yolomy-service
    app: yolomy-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    name: yolo-client-pod
    app: yolomy-app